export const DIARY_LIST_REQUEST = 'DIARY_LIST_REQUEST';
export const DIARY_LIST_SUCCESS = 'DIARY_LIST_SUCCESS';
export const DIARY_LIST_FAIL = 'DIARY_LIST_FAIL';

export const DIARY_DETAILS_REQUEST = 'DIARY_DETAILS_REQUEST';
export const DIARY_DETAILS_SUCCESS = 'DIARY_DETAILS_SUCCESS';
export const DIARY_DETAILS_FAIL = 'DIARY_DETAILS_FAIL';
